# Model Persistence

Model Persistence is  saving of a model for future use. <br>
This eliminates the need to train the model again everytime <br>

In [1]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [2]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
X_features=iris_dataset.data

In [5]:
Y_target=iris_dataset.target

In [6]:
#values to be predicted
X_new=[[3,5,4,1],[5,3,4,2]]

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logReg=LogisticRegression()

In [9]:
import warnings
warnings.filterwarnings('ignore')
logReg.fit(X_features,Y_target)

LogisticRegression()

In [10]:
logReg.predict(X_new)

array([0, 1])

#### Saving the model

In [11]:
#import the library for model persistence
import pickle as pkl

In [12]:
persist_model=pkl.dumps(logReg)

In [13]:
persist_model

b'\x80\x04\x95\x03\x03\x00\x00\x00\x00\x00\x00\x8c\x1esklearn.linear_model._logistic\x94\x8c\x12LogisticRegression\x94\x93\x94)\x81\x94}\x94(\x8c\x07penalty\x94\x8c\x02l2\x94\x8c\x04dual\x94\x89\x8c\x03tol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rfit_intercept\x94\x88\x8c\x11intercept_scaling\x94K\x01\x8c\x0cclass_weight\x94N\x8c\x0crandom_state\x94N\x8c\x06solver\x94\x8c\x05lbfgs\x94\x8c\x08max_iter\x94Kd\x8c\x0bmulti_class\x94\x8c\x04auto\x94\x8c\x07verbose\x94K\x00\x8c\nwarm_start\x94\x89\x8c\x06n_jobs\x94N\x8c\x08l1_ratio\x94N\x8c\x0en_features_in_\x94K\x04\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x1c\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x0c\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x94t\x94b\x8c\x07n_iter_\x9

In [14]:
#use joblib.dump to persist the model to a file
import joblib

In [15]:
joblib.dump(logReg,'regresfilename.pkl')

['regresfilename.pkl']

In [16]:
#we use the joblib.load to persist the model to a file
#create the new estimator for the saved model
new_logreg_estimator=joblib.load('regresfilename.pkl')

In [17]:
new_logreg_estimator

LogisticRegression()

In [18]:
new_logreg_estimator.predict(X_new)

array([0, 1])

## Model Evaluation: Metric Functions

scikit learn's metric function i sused to evaluate models <br>
It is important to evaluate a model's accuracy and 